# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc413f2d6fac91bcbb0ebfcf8f481674531dae684d4286cfacb86de2c5662260236c0602830d1a49df836b4eed928fd649912917b22ee08814e75b850a6a39ee
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_api_key:  <%= ENV["MANDRILL_API_KEY"] %>
  return_url_key: /ZyV25JsB8W4Ff3gKAn0do9d33/fjAg4Cnki9GHp6i4=
  return_url_iv: fWl+FVOMxuu2yP4RynBU/w==
  facebook_secret: <%= ENV["FACEBOOK_APP_SERCRET"] %>

test:
  secret_key_base: b000fbaf8b967cc39d76d8ff8718d5493ffecf624c33eb6953d32b3d489e6b9f768a335d784d17eff67fa96ec9d11195689620808a8cf48a204fc4de7db558b9
  return_url_key: /ZyV25JsB8W4Ff3gKAn0do9d33/fjAg4Cnki9GHp6i4=
  return_url_iv: fWl+FVOMxuu2yP4RynBU/w==

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"]%>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_api_key:  <%= ENV["MANDRILL_API_KEY"] %>
  return_url_key: <%= ENV["CARTSTASH_RETURNURL_KEY"]%>
  return_url_iv: <%= ENV["CARTSTASH_RETURNURL_IV"]%>
  facebook_secret: <%= ENV["FACEBOOK_APP_SERCRET"] %>

